/*
Measures department efficiency using average length of stay.
Departments with lower averages are considered more efficient.
*/
SELECT
	DEP.DEPARTMENT_NAME,
	ROUND(AVG(A.DISCHARGE_DATE - A.ADMISSION_DATE), 2) AS AVG_LENGTH_OF_STAY,
	COUNT(A.ADMISSION_ID) AS TOTAL_ADMISSIONS
FROM
	DEPARTMENTS DEP
	JOIN DOCTORS D ON DEP.DEPARTMENT_ID = D.DEPARTMENT_ID
	JOIN ADMISSIONS A ON D.DOCTOR_ID = A.DOCTOR_ID
GROUP BY
	DEP.DEPARTMENT_NAME
ORDER BY
	AVG_LENGTH_OF_STAY