CREATE TABLE IF NOT EXISTS DEPARTMENTS (
	DEPARTMENT_ID SERIAL PRIMARY KEY,
	DEPARMENT_NAME TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS DOCTORS (
	DOCTOR_ID SERIAL PRIMARY KEY,
	FIRST_NAME TEXT NOT NULL,
	LAST_NAME TEXT NOT NULL,
	DEPARTMENT_ID INTEGER REFERENCES DEPARTMENTS (DEPARTMENT_ID)
);

CREATE TABLE PATIENTS (
	PATIENT_ID SERIAL PRIMARY KEY,
	FIRST_NAME TEXT NOT NULL,
	LAST_NAME TEXT NOT NULL,
	BIRTH_DATE DATE,
	GENDER CHAR(1)
);

CREATE TABLE ADMISSIONS (
	ADMISSION_ID SERIAL PRIMARY KEY,
	PATIENT_ID INTEGER REFERENCES PATIENTS (PATIENT_ID),
	DOCTOR_ID INTEGER REFERENCES DOCTORS (DOCTOR_ID),
	ADMISSION_DATE DATE NOT NULL,
	DISCHARGE_DATE DATE
);

CREATE TABLE TREATMENTS (
	TREATMENT_ID SERIAL PRIMARY KEY,
	ADMISSION_ID INTEGER REFERENCES ADMISSIONS (ADMISSION_ID),
	TREATMENT_NAME TEXT NOT NULL,
	TREATMENT_COST NUMERIC(10, 2) NOT NULL
)