/*
Ranks doctors by total number of admissions handled.
Used to identify high workload and potential bottlenecks.
*/
SELECT
	D.DOCTOR_ID,
	CONCAT(D.FIRST_NAME, ' ', D.LAST_NAME) AS DOCTOR_NAME,
	COUNT(A.ADMISSION_DATE) AS TOTAL_ADMISSIONS,
	RANK() OVER (
		ORDER BY
			COUNT(A.ADMISSION_ID) DESC
	) AS WORKLOAD_RANK
FROM
	DOCTORS D
	JOIN ADMISSIONS A ON D.DOCTOR_ID = A.DOCTOR_ID
GROUP BY
	D.DOCTOR_ID,
	DOCTOR_NAME
ORDER BY
	TOTAL_ADMISSIONS DESC
