/*
Analyzes treatment costs by type.
Shows both average and total cost per treatment.
*/
SELECT
	TREATMENT_NAME,
	ROUND(SUM(TREATMENT_COST), 2) AS TOTAL_TREATMENT_COST,
	ROUND(AVG(TREATMENT_COST), 2) AS AVG_COST,
	COUNT(*) AS TOTAL_TREATMENTS
FROM
	TREATMENTS
GROUP BY
	TREATMENT_NAME
ORDER BY
	TOTAL_TREATMENT_COST DESC