/*
Identifies admissions with the highest total treatment cost.
Useful for cost control and case review.
*/
SELECT
	A.ADMISSION_ID,
	CONCAT(P.FIRST_NAME, ' ', P.LAST_NAME) AS PATIENT_NAME,
	ROUND(SUM(T.TREATMENT_COST), 2) AS TOTAL_ADMISSION_COST
FROM
	ADMISSIONS A
	JOIN TREATMENTS T ON A.ADMISSION_ID = T.ADMISSION_ID
	JOIN PATIENTS P ON A.PATIENT_ID = P.PATIENT_ID
GROUP BY
	A.ADMISSION_ID,
	PATIENT_NAME
ORDER BY
	TOTAL_ADMISSION_COST DESC
LIMIT
	10